import type { Metadata } from "next";

import "@/app/ui/globals.css";
import { montserrat } from "@/app/ui/fonts";

import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",  
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
